[graph]
# Only check Linux as that's all we care for
targets = ["x86_64-unknown-linux-gnu"]

[advisories]
version = 2
ignore = []
yanked = "deny"

[licenses]
version = 2
allow = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "EUPL-1.2", "Unicode-3.0", "Zlib"]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
